<?php

namespace Heyday\SilverStripe\WkHtml\Input;

use SilverStripe\Dev\SapphireTest;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-27 at 21:09:32.
 */
class TemplateTest extends SapphireTest
{
    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
//        $this->object = new Template;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::setTemplate
     * @todo   Implement testSetTemplate().
     */
    public function testSetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::getTemplate
     * @todo   Implement testGetTemplate().
     */
    public function testGetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::setTemplateFromString
     * @todo   Implement testSetTemplateFromString().
     */
    public function testSetTemplateFromString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::getData
     * @todo   Implement testGetData().
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Input\Template::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
