<?php
namespace Heyday\SilverStripe\WkHtml\Output;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-27 at 21:11:03.
 */
class BrowserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Browser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Browser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\Output\Browser::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
