<?php
namespace Heyday\SilverStripe\WkHtml\Output;

use SilverStripe\Dev\SapphireTest;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-28 at 12:35:22.
 */
class RandomFileTest extends SapphireTest
{
    /**
     * @var RandomFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
//        $this->object = new RandomFile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers \Heyday\SilverStripe\WkHtml\Output\RandomFile::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
