<?php
namespace Heyday\SilverStripe\WkHtml;

use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\SapphireTest;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-28 at 12:40:14.
 */
class ImageHelperTest extends SapphireTest
{
    /**
     * @var ImageHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = Injector::inst()->get(ImageHelper::class);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\ImageHelper::extraStatics
     * @todo   Implement testExtraStatics().
     */
    public function testExtraStatics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\ImageHelper::Base64
     * @todo   Implement testBase64().
     */
    public function testBase64()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
