<?php
namespace Heyday\SilverStripe\WkHtml\Output;

use org\bovigo\vfs\vfsStream;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-28 at 12:35:11.
 */
class FileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException RuntimeException
     * @expectedExceptionMessage File already exists.
     */
    public function testFileExists()
    {
        vfsStream::setup(
            'root',
            null,
            array(
                'test.pdf' => ''
            )
        );
        new File('vfs://root/test.pdf');
    }
    /**
     * @expectedException RuntimeException
     * @expectedExceptionMessage Directory is not writable.
     */
    public function testDirectoryNotWritable()
    {
        vfsStream::setup(
            'root',
            0000
        );
        new File('vfs://root/test.pdf');
    }
    public function testProcess()
    {
        vfsStream::setup(
            'root'
        );
        $file = new File($path = 'vfs://root/test.pdf');
        $generator = $this->getMock('Knp\Snappy\GeneratorInterface');
        $generator->expects($this->once())
            ->method('generateFromHtml')
            ->with(
                $this->equalTo('test'),
                $this->equalTo($path),
                $this->equalTo(array()),
                $this->equalTo(false)
            );
        $file->process('test', $generator);
    }
    public function testProcessOverwrite()
    {
        vfsStream::setup(
            'root',
            null,
            array(
                'test.pdf' => ''
            )
        );
        $file = new File($path = 'vfs://root/test.pdf', true);
        $generator = $this->getMock('Knp\Snappy\GeneratorInterface');
        $generator->expects($this->once())
            ->method('generateFromHtml')
            ->with(
                $this->equalTo('test'),
                $this->equalTo($path),
                $this->equalTo(array()),
                $this->equalTo(true)
            );
        $file->process('test', $generator);
    }
}
