<?php
namespace Heyday\SilverStripe\WkHtml;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-27 at 21:09:17.
 */
class GeneratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Generator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Generator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\Generator::setInputter
     * @todo   Implement testSetInputter().
     */
    public function testSetInputter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\Generator::setOutputter
     * @todo   Implement testSetOutputter().
     */
    public function testSetOutputter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\Generator::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
