<?php
namespace Heyday\SilverStripe\WkHtml;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-28 at 12:40:25.
 */
class TemplateHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TemplateHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TemplateHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\TemplateHelper::EmbedCss
     * @todo   Implement testEmbedCss().
     */
    public function testEmbedCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\SilverStripe\WkHtml\TemplateHelper::EmbedBase64Image
     * @todo   Implement testEmbedBase64Image().
     */
    public function testEmbedBase64Image()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
